PUTIFSCHK.MODULE: private OPTIMIZE = 40
PUTIFSCHK.MODULE: private INLINE = *ON *AUTO *NOLIMIT *NOLIMIT *YES
PUTIFSCHK.MODULE: private DBGVIEW = *NONE
PUTIFSCHK.MODULE:PUTIFSCHK.C
PUTIFSCHK.PGM: private ACTGRP := *CALLER
PUTIFSCHK.PGM: PUTIFSCHK.MODULE
PUTIFS.PGM: PUTIFS.PGM.C
PUTIFS.PGM: private ALWUPD := *NO
PUTIFS.PGM: private USRPRF := *OWNER