PUTIFSCHK.MODULE: private OPTIMIZE = 40
PUTIFSCHK.MODULE: private INLINE = *ON *AUTO *NOLIMIT *NOLIMIT *YES
PUTIFSCHK.MODULE: private DBGVIEW = *NONE
PUTIFSCHK.MODULE:PUTIFSCHK.C
PUTIFSCHK.PGM: private ACTGRP := *CALLER
PUTIFSCHK.PGM:PUTIFSCHK.MODULE


