# SUBDIRS = functionsVAT QDDSSRC QCMDSRC QILESRVSRC QILESRC QSQLSRC QMSGSRC
# SUBDIRS = QILESRVSRC QILESRC QSQLSRC QMSGSRC QDTASRC QPNLSRC
# SUBDIRS = QCMDSRC QDTASRC QILESRVSRC QPNLSRC QSQLSRC functionsVAT QBNDSRC QCLSRC QDDSSRC QILESRC QMSGSRC QSRVSRC

#SUBDIRS = QCBLSRC QCMDSRC QDTASRC QILESRVSRC QPNLSRC QSQLSRC functionsVAT QBNDSRC QCLSRC QDDSSRC QILESRC QMSGSRC QRPGSRC QSRVSRC QRPGLESRC
SUBDIRS = functionsVAT QDDSSRC QDTASRC QPNLSRC QCLSRC QMSGSRC QRPGSRC QRPGLESRC QCBLSRC QSRVSRC QILESRVSRC QBNDSRC QILESRC QCMDSRC 
