SRVPGMs := FARTICLE.SRVPGM FCOUNTRY.SRVPGM FCUSTOMER.SRVPGM FFAMILLY.SRVPGM FPROVIDER.SRVPGM

FARTICLE.SRVPGM: $(d)/FARTICLE.BND
FCOUNTRY.SRVPGM: $(d)/FCOUNTRY.BND
FCUSTOMER.SRVPGM: $(d)/FCUSTOMER.BND
FFAMILLY.SRVPGM: $(d)/FFAMILLY.BND
FPROVIDER.SRVPGM: $(d)/FPROVIDER.BND