PFs := VATDEF.FILE SAMREF.FILE
MODULEs := VAT300.MODULE
SRVPGMs := FVAT.SRVPGM

SAMREF.FILE: $(d)/SAMREF.PF

VAT300.MODULE: $(d)/VAT300.RPGLE

FVAT.SRVPGM: $(d)/FVAT.BND VAT300.MODULE

VATDEF.FILE: $(d)/VATDEF.PF SAMREF.FILE
