PFs += VATDEF.FILE SAMREF.FILE
MODULEs += VAT300.MODULE
SRVPGMs += FVAT.SRVPGM

VAT300.MODULE: VAT300.RPGLE VATDEF.FILE SAMREF.FILE
FVAT.SRVPGM: FVAT.BND VAT300.MODULE
VATDEF.FILE: VATDEF.PF SAMREF.FILE
SAMREF.FILE: SAMREF.PF

