PFs := VATDEF.FILE
MODULEs := VAT300.MODULE
SRVPGMs := FVAT.SRVPGM

VAT300.MODULE: VAT300.RPGLE VAT.RPGLEINC

FVAT.SRVPGM: FVAT.BND VAT300.MODULE
FVAT.SRVPGM: TEXT = Functions VAT

VATDEF.FILE: VATDEF.PF SAMREF.FILE
