CRTSBSD.FILE:
	system -i "CRTSBSD SBSD($(OBJLIB)/BATCHSBSD) POOLS((1 *SHRPOOL3 *N *MB))"
CHGSBSD.FILE:
	system -i "CHGSBSD SBSD($(OBJLIB)/BATCHSBSD) POOLS((3 8000 999 *MB))"
CRTJOBQ.FILE:
	system -i "CRTJOBQ JOBQ($(OBJLIB)/BWLJOBQ)"
CRTJOBD.FILE:
	system -i "CRTJOBD JOBD($(OBJLIB)/BWLJOBD) JOBQ($(OBJLIB)/BWLJOBQ) LOG(4 40 *MSG)"
ADDJOBQE.FILE:
	system -i "ADDJOBQE SBSD($(OBJLIB)/BATCHSBSD) JOBQ($(OBJLIB)/BWLJOBQ) MAXACT(*NOMAX) SEQNBR(15)"
CRTCLS.FILE:
	system -i "CRTCLS CLS($(OBJLIB)/BWLCLASS) RUNPTY(30) TIMESLICE(5000)"
ADDRTGE1.FILE:
	system -i "ADDRTGE SBSD($(OBJLIB)/BATCHSBSD) SEQNBR(9999) CMPVAL(*ANY) PGM(QSYS/QCMD) CLS($(OBJLIB)/BWLCLASS) POOLID(3)"
