SQLs := ART801.PGM ARTLSTDAT.FILE ORD701.PGM ARTIINF.FILE CUSSEQ.DTAARA  ORDERCUS.FILE
# ISOTODATE.SRVPGM ISOTODATE4.SRVPGM
ART801.PGM: $(d)/ART801.SQLPRC
ARTLSTDAT.FILE: $(d)/ARTLSTDAT.VIEW
ISOTODATE.SRVPGM: $(d)/ISOTODATE.SQLUDF
ORD701.PGM: $(d)/ORD701.SQLTRG
ARTIINF.FILE: $(d)/ARTIINF.TABLE
CUSSEQ.DTAARA: $(d)/CUSSEQ.SQLSEQ
ISOTODATE4.SRVPGM: $(d)/ISOTODATE4.SQLUDF
ORDERCUS.FILE: $(d)/ORDERCUS.VIEW