SQLs := ART801.SQL ARTLSTDAT.SQL ISOTODATE.SQL ORD701.SQL ARTIINF.SQL CUSSEQ.SQL ISOTODATE4.SQL ORDERCUS.SQL

ART801.SQL: $(d)/ART801.SQLPRC
ARTLSTDAT.SQL: $(d)/ARTLSTDAT.VIEW
ISOTODATE.SQL: $(d)/ISOTODATE.SQLUDF
ORD701.SQL: $(d)/ORD701.SQLTRG
ARTIINF.SQL: $(d)/ARTIINF.TABLE
CUSSEQ.SQL: $(d)/CUSSEQ.SQLSEQ
ISOTODATE4.SQL: $(d)/ISOTODATE4.SQLUDF
ORDERCUS.SQL: $(d)/ORDERCUS.VIEW