SRVPGMs := FARTICLE.SRVPGM FCUSTOMER.SRVPGM FPARAMETER.SRVPGM FCOUNTRY.SRVPGM FFAMILLY.SRVPGM FPROVIDER.SRVPGM LOG.SRVPGM

FARTICLE.SRVPGM: $(d)/FARTICLE.ILESRVPGM ART300.MODULE ART301.MODULE FFAMILLY.SRVPGM
FCUSTOMER.SRVPGM: $(d)/FCUSTOMER.ILESRVPGM CUS300.MODULE CUS301.MODULE
FPARAMETER.SRVPGM: $(d)/FPARAMETER.ILESRVPGM PAR300.MODULE
FCOUNTRY.SRVPGM: $(d)/FCOUNTRY.ILESRVPGM COU300.MODULE COU301.MODULE
FFAMILLY.SRVPGM: $(d)/FFAMILLY.ILESRVPGM FAM300.MODULE FAM301.MODULE
FPROVIDER.SRVPGM: $(d)/FPROVIDER.ILESRVPGM PRO300.MODULE
LOG.SRVPGM: $(d)/LOG.ILESRVPGM LOG300.MODULE