SRVPGMs := FARTICLE.SRVPGM FCUSTOMER.SRVPGM FPARAMETER.SRVPGM FCOUNTRY.SRVPGM FFAMILLY.SRVPGM FPROVIDER.SRVPGM LOG.SRVPGM

FARTICLE.SRVPGM: $(d)/FARTICLE.ILESRVPGM
FCUSTOMER.SRVPGM: $(d)/FCUSTOMER.ILESRVPGM
FPARAMETER.SRVPGM: $(d)/FPARAMETER.ILESRVPGM
FCOUNTRY.SRVPGM: $(d)/FCOUNTRY.ILESRVPGM
FFAMILLY.SRVPGM: $(d)/FFAMILLY.ILESRVPGM
FPROVIDER.SRVPGM: $(d)/FPROVIDER.ILESRVPGM
LOG.SRVPGM: $(d)/LOG.ILESRVPGM